### PR TITLE
Remove google analytics code

### PR DESCRIPTION
**Pull request by attogram**
Remove google analytics code for cleaner deployments

### CODE REVIEW

**Comment by blaze33** [comment]
Hi, I do get the issue of having an hardcoded GA code but I'm not ready to just remove the associated code.

A possible solution could be like https://www.colbyfayock.com/2018/08/reliable-and-maintainable-google-analytics-in-webpack where optional templates are included and/or modified into the final index.html

What was the bug that caused you to remove the GA code ?

**Comment by attogram** [comment]
Yes.  Some sort of optional setup, with the default being absolutely no tracking, would be good.

**Comment by blaze33** [comment]
Okay, here you go: 1014235f9daf31b15b9171cfe200ca20ce11b0b0
Default is now no analytics at all.
To use GA you can now create a .env file following the .env.example syntax.
```
ANALYTICS=true
GA_PROPERTY_ID=UA-XXXXXXXX-X
```
Cheers

**Comment by attogram** [comment]
That is great!   I really like the .env setup.   Thanks!

**Pull request closed without merging**
